const LIMITS = {
  MAX_PHOTOS: 5,
  MAX_VIDEO_MINUTES: 10,
  MAX_VIDEO_BYTES: 250 * 1024 * 1024,
  TITLE: { MIN: 5, MAX: 255 },
  DESCRIPTION: { MIN: 10, MAX: 5000 },
  COORDINATES: {
    LAT: { MIN: -90, MAX: 90 },
    LNG: { MIN: -180, MAX: 180 },
  },
  DEDUP: {
    RADIUS_METERS: 1000,
    TIME_HOURS: 4,
    MAX_CANDIDATES: 20,
  },
  ML: {
    TOXICITY_THRESHOLD: 0.2,
    RISK_HIGH: 0.5,
    RISK_AUTOFLAG: 0.8,
  },
  CONSTELLATION: {
    RADIUS_METERS: 500,
    EXPIRY_HOURS: 2,
    ELIGIBILITY_WINDOW_MINUTES: 30,
    CREATION_LIMIT: 2,
    CREATION_WINDOW_MINUTES: 60,
    CORROBORATION_LIMIT: 10,
    CORROBORATION_WINDOW_MINUTES: 60,
    PUSH_COOLDOWN_MINUTES: 15,
    PUSH_HOURLY_LIMIT: 3,
    NOTE_MAX_LENGTH: 280,
  },
};

module.exports = {
  LIMITS,
};
